name: Tests
on: [push]
jobs:
  tests:
    runs-on: ubuntu-latest
    name: Tests
    steps:
      - uses: actions/checkout@v2
      - run: echo "this is a test" > test.txt
      - uses: ./
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          target-branch: "test-branch"
          commit-message: "This is a test commit"
          path: |
            LICENSE
            README.md
            test.txt
