name: Tests
on: [push]
jobs:
  tests:
    runs-on: ubuntu-latest
    name: Tests
    steps:
      - uses: actions/checkout@v2

      - uses: ./
        with:
          target-branch: "test-branch"
          commit-message: "This is a test commit"
          path: LICENSE .github/workflows

      - uses: ./
        with:
          commit-message: "Default suffix"
          path: |
            LICENSE
            README.md
